### ISSUE TITLE
NextPush crashes instead of sending RegistrationFailed when not logged in

### ISSUE THREAD

**Issue by karmanyaahm** [UP-NextPush/android#12]
```log
FATAL EXCEPTION: main
E/AndroidRuntime(15961): Process: org.unifiedpush.distributor.nextpush, PID: 15961
E/AndroidRuntime(15961): java.lang.RuntimeException: Unable to start receiver org.unifiedpush.distributor.nextpush.receivers.RegisterBroadcastReceiver: kotlin.UninitializedPropertyAccessException: lateinit property ssoAccount has not been initialized
E/AndroidRuntime(15961):        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3798)
E/AndroidRuntime(15961):        at android.app.ActivityThread.access$1400(ActivityThread.java:220)
E/AndroidRuntime(15961):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1871)
E/AndroidRuntime(15961):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(15961):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(15961):        at android.app.ActivityThread.main(ActivityThread.java:7403)
E/AndroidRuntime(15961):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15961):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(15961):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
E/AndroidRuntime(15961): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property ssoAccount has not been initialized
E/AndroidRuntime(15961):        at org.unifiedpush.distributor.nextpush.account.AccountUtilsKt.getSsoAccount(AccountUtils.kt:30)
E/AndroidRuntime(15961):        at org.unifiedpush.distributor.nextpush.api.ApiUtilsKt.cApi(ApiUtils.kt:54)
E/AndroidRuntime(15961):        at org.unifiedpush.distributor.nextpush.api.ApiUtilsKt.apiCreateApp(ApiUtils.kt:164)
E/AndroidRuntime(15961):        at org.unifiedpush.distributor.nextpush.receivers.RegisterBroadcastReceiver.onReceive(RegisterBroadcastReceiver.kt:34)
E/AndroidRuntime(15961):        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3789)
E/AndroidRuntime(15961):        ... 8 more
```

I think the title is what is happening, though I haven't looked too deep into this.

**Comment by p1gp1g** [comment]
https://github.com/UP-NextPush/android/commit/1ab3eaa83a2387bb0b866af334372e9984a8cce4 should have fixes it. It need to be improved : https://github.com/UP-NextPush/android/issues/20
